language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - ".+"
  notifications:
    email: false
env:
  secure: "qqxl0nA0Bc/1aZiZzZme3AfSnyvVB7oRHWX3InXkTGN50rMFhlrQXZungPoItY582z/BSCUfOd5jaeMWtgTSsvKKidKKVyBKwwOtToAUSBjcadPbcN0/a/g0HwdjFQFI9nr32mACx6m2ptAmquC5RhZxwkGwTcgvrbmrcwDyMkxOAgsviHobrA6VsEPNbdMrNLvJLmkZ8y1h7i86plhW78uxHoFAt1fiSTYII/19IyKTf9GH6QC380vR3s7qjG6s6HKb3pPp/0uaU/tVb4SnuT8tX/dSWBbnGPa85edpJjabyvDE4xT9mWS/yT7QV3RSnm2tEgrf5SXPChA8B7U4lkeHHNNSiH22MoIVl3KtlifPky4/bkunejbfbgssb8SeTSe0uog5FdGORjvYnJzRAaUPl34mipzMBnp/VXRU7DA+V6IpUsfd/ElCyMKwZ/bquXRjHthl0Sfx3RM0/FJ/EuaA+X8zLdV680dIkCr7rx8Kh3BwX0gneFic19C0I2GP024pohF3G61FvOZtVBUwygUc/X5oQ4OAMlOGjpZHDH8twRMwAABNyF5DlUbxSw77/HVjJGBE17imai+I2jk4T7NMularuYqNSAskMFBtmwexY+GbVl6Sn+ITGpGl+fYKmJwwR80XQQ8er38mq9t9oO/+cBYF9aMbLOQbI6ptB70="

after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^feature/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=tallerii/foodie-android /tmp/travis-automerge"